### ISSUE TITLE
start.sh requires disunified_net.py which is not in the repo

### ISSUE THREAD

**Issue by steven5clu884** [ChongjianGE/DCTON#8]
start.sh requires disunified_net.py, but this file is not located in the repository.
Please provide this file and any other required files.
Thank you in advance.

**Comment by ChongjianGE** [comment]
Hi @steven5clu884 
Thanks for your interest in our work.  We have provided the files. Please have a check.

**Comment by steven5clu884** [comment]
Thank you so much for your response, and your time and attention.

My best wishes to you and your loved ones
