### ISSUE TITLE
why can not find the inference result of demo? I mean the infer-picture? can you update for this?

### ISSUE THREAD

**Issue by CuiShaohua** [ChongjianGE/DCTON#9]
why can not find the inference result of demo? I mean the infer-picture? can you update for this?

**Comment by ChongjianGE** [comment]
Hi @CuiShaohua 

You can change the path for saving the inference results.
https://github.com/ChongjianGE/DCTON/blob/1bc2cbdbbb9988c7937d4d328437fcfb7999c382/models/dcton_model.py#L270
